### ISSUE TITLE
urdf file seems to be wrong

### ISSUE THREAD

**Issue by Timkeeper2018** [soshishimada/Neural_Physcap_Demo#3]
when I try to load urdf mode(manual.urdf) use **rbdl.loadModel** , the program reported some errors.
I am in the ubuntu20.04 environment and use the **rbdl-orb** library for loading (with little difference from rbdl). I didn't get similar errors when I tried to load other urdf files when I suspected it was my environment.

```
terminate called after throwing an instance of 'urdf::URDFParseError'
  what():  Parser found 1 elements but 3 expected while parsing vector [0.0]
```

**Comment by soshishimada** [comment]
Can you try rbdl V.2.6.0., not rbdl-orb ? I cannot help with the loader issues of the third-party scripts. With rbdl v.2.6.0, my colleagues could run the code with no loading errors.

**Comment by qingchuanma** [comment]
But I got the same error when I try to model use rbdl library.

**Comment by mornfairy** [comment]
> 你可以试试 rbdl V.2.6.0.，而不是 rbdl-orb 吗？我无法帮助解决第三方脚本的加载程序问题。使用 rbdl v.2.6.0，我的同事可以运行代码而不会出现加载错误。

Hello, how do I get the rbdl V.2.6.0 version?  I couldn't find it after an extensive search.

**Comment by Xianjin111** [comment]
> > 你可以试试 rbdl V.2.6.0.，而不是 rbdl-orb 吗？我无法帮助解决第三方脚本的加载程序问题。使用 rbdl v.2.6.0，我的同事可以运行代码而不会出现加载错误。
> 
> Hello, how do I get the rbdl V.2.6.0 version? I couldn't find it after an extensive search.

Hi~ I have the same question. Have you deal with it?

I use the latested version. It always has the error:"AttributeError: module 'rbdl' has no attribute 'loadModel". Have you met the same problem?

Thx~

**Comment by guoti777** [comment]
fix this error here:
link name = "head_marker"
		inertial
			origin rpy = "0 0 0"  xyz = "0.0" 
			mass value =  "0.00001" 
			nertia ixx = "0.1" ixy = "0" ixz = "0" iyy = "0.1" iyz = "0" izz = "0.1" 
	inertial


 xyz = "0.0" />  to  xyz = "0.0 0.0 0.0" />

**Comment by guoti777** [comment]
fix this error here:
"	<link name = "head_marker">
		<inertial>
			<origin rpy = "0 0 0"  xyz = "0.0" />
			<mass value =  "0.00001" />"
-------- 

xyz = "0.0" /> to xyz = "0.0 0.0 0.0" />
