### ISSUE TITLE
DyNet network dimension doesn't match  the input.

### ISSUE THREAD

**Issue by HitLyn** [soshishimada/Neural_Physcap_Demo#5]
Hi,
I got the error below while trying to run the demo:
```
Warning: joint unsupported, creating a fixed joint instead.Traceback (most recent call last):
  File "demo.py", line 365, in <module>
    IPL.inference()
  File "demo.py", line 262, in inference
    neural_gain, neural_offset = self.DyNet(dynInput )#.cuda()
  File "/homeL/cong/anaconda3/envs/neural-physcap/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homeL/cong/HitLyn/Neural_Physcap_Demo/networks.py", line 42, in forward
    x = self.LReLU( self.fc1(x))#)
  File "/homeL/cong/anaconda3/envs/neural-physcap/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homeL/cong/anaconda3/envs/neural-physcap/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/homeL/cong/anaconda3/envs/neural-physcap/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2590 and 2302x1024)
```
I looked into the code and find the python code here:

https://github.com/soshishimada/Neural_Physcap_Demo/blob/b3a4a30094420b21c1cf15f11b0cc28fe33a0b17/demo.py#L261-L262

The dimension of dynInput is [1, 2590], which doesn't match the first layer of self.DyNet [2302, 1024].

Could you please help to figure out this problem?

**Comment by HitLyn** [comment]
Problem solved, it's because of the wrong version of rbdl.
Make sure your rbdl version is V2.6.0 as recommended.

**Comment by luoww1992** [comment]
@HitLyn , i have the same question with rbdlv 2.6.0.
what is your env?
how to build the rbdl with your cmake cmd(my cmd is : cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_ADDON_URDFREADER=ON -D RBDL_BUILD_PYTHON_WRAPPER=ON ..
) ?

**Comment by HitLyn** [comment]
> @HitLyn , i have the same question with rbdlv 2.6.0. what is your env? how to build the rbdl with your cmake cmd(my cmd is : cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_ADDON_URDFREADER=ON -D RBDL_BUILD_PYTHON_WRAPPER=ON .. ) ?

Make sure you are using the original rbdl library. The rbdl-orb can cause this dimension mismatching.

**Comment by luoww1992** [comment]
@HitLyn , yes ,i use the original rbdl library. then checkout v2.6.0 , download iand build it, 
and then show the error

**Comment by luoww1992** [comment]
@HitLyn 
what is your detail env? 
my cmake cmd is :
   cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_ADDON_URDFREADER=ON -D RBDL_BUILD_PYTHON_WRAPPER=ON .. 
some wrong?

**Comment by luoww1992** [comment]
@HitLyn , can you help me ?

**Comment by HitLyn** [comment]
> 

Hi, your build options seem to be no problem. I am quite sure that my problem is caused by using the rbdl-orb, in which they change the output dimension. The original rbdl doesn't cause this problem, even though you may meet another build problem when the URDFREADER is on, but that is different question.

**Comment by xjchao7** [comment]
> Problem solved, it's because of the wrong version of rbdl. Make sure your rbdl version is V2.6.0 as recommended.

Hi~I would like to ask where could I download the v2.6.0 for rbdl. I use the latest rbdl version, it ofter has error:"AttributeError: module 'rbdl' has no attribute 'loadModel".

Could you please tell me how to deal with it?

Thx~
